// =====================================================
// DEVOTIONAL SERIES TYPES
// =====================================================

export type DifficultyLevel = 'beginner' | 'intermediate' | 'advanced';

export interface ScriptureRef {
  book: string;
  chapter: number;
  verseStart: number;
  verseEnd?: number;
}

export interface DevotionalSeries {
  id: string;
  slug: string;
  title: string;
  description: string;
  coverImageUrl?: string;
  totalDays: number;
  topics: string[];
  isSeasonal: boolean;
  seasonStartMonth?: number;
  seasonStartDay?: number;
  difficultyLevel: DifficultyLevel;
  createdAt: Date;
}

export interface DevotionalDay {
  id: string;
  seriesId: string;
  dayNumber: number;
  title: string;
  scriptureRefs: ScriptureRef[];
  contentPrompt: string;
  reflectionQuestions: string[];
  prayerFocus?: string;
  createdAt: Date;
}

// =====================================================
// USER ENROLLMENT TYPES
// =====================================================

export interface UserSeriesEnrollment {
  id: string;
  userId: string;
  seriesId: string;
  series?: DevotionalSeries; // Joined data
  enrolledAt: Date;
  currentDay: number;
  completedDays: number[];
  isActive: boolean;
  isPrimary: boolean;
  lastActivityAt: Date;
  reminderTime: string; // TIME format "HH:mm:ss"
  createdAt: Date;
}

export interface EnrollmentProgress {
  enrollmentId: string;
  seriesId: string;
  seriesTitle: string;
  seriesSlug: string;
  totalDays: number;
  currentDay: number;
  completedDays: number[];
  isPrimary: boolean;
  isActive: boolean;
  progressPercentage: number;
  daysRemaining: number;
  lastActivityAt: Date;
}

// =====================================================
// ONBOARDING TYPES
// =====================================================

export type TimeAvailable = '5-10min' | '10-20min' | '20+min';
export type ExperienceLevel = 'new' | 'growing' | 'deep';
export type LifeStage = 'single' | 'married' | 'parent' | 'empty_nester';

export interface OnboardingResponses {
  id?: string;
  userId?: string;
  lifeAreaFocus?: string;
  timeAvailable?: TimeAvailable;
  experienceLevel?: ExperienceLevel;
  lifeStage?: LifeStage;
  completedAt?: Date;
}

// Quiz question configuration
export interface QuizQuestion {
  id: string;
  question: string;
  options: QuizOption[];
  field: keyof OnboardingResponses;
  isRequired: boolean;
}

export interface QuizOption {
  value: string;
  label: string;
  description?: string;
  icon?: string;
  mapsToSeries?: string; // Series slug this option maps to
}

// =====================================================
// DAILY DEVOTIONAL CONTENT
// =====================================================

export interface DailyDevotionalContent {
  day: DevotionalDay;
  series: DevotionalSeries;
  enrollment: UserSeriesEnrollment;
  scriptureText: string; // Actual verse text fetched from DB
  aiReflection?: string; // Generated by AI
  isCompleted: boolean;
}

// =====================================================
// SERIES RECOMMENDATION
// =====================================================

export interface SeriesRecommendation {
  series: DevotionalSeries;
  matchScore: number;
  matchReasons: string[];
}

// =====================================================
// NOTIFICATION TYPES
// =====================================================

export interface DevotionalReminder {
  id: string;
  enrollmentId: string;
  seriesTitle: string;
  scheduledTime: Date;
  notificationId?: string; // Expo notification ID
}

// =====================================================
// UI STATE TYPES
// =====================================================

export interface DevotionalHubState {
  primaryEnrollment?: EnrollmentProgress;
  otherEnrollments: EnrollmentProgress[];
  recommendedSeries: DevotionalSeries[];
  todayCompleted: boolean;
  currentStreak: number;
}

// =====================================================
// DATABASE ROW TYPES (for Supabase)
// =====================================================

export interface DevotionalSeriesRow {
  id: string;
  slug: string;
  title: string;
  description: string;
  cover_image_url: string | null;
  total_days: number;
  topics: string[];
  is_seasonal: boolean;
  season_start_month: number | null;
  season_start_day: number | null;
  difficulty_level: string;
  created_at: string;
}

export interface DevotionalDayRow {
  id: string;
  series_id: string;
  day_number: number;
  title: string;
  scripture_refs: ScriptureRef[];
  content_prompt: string;
  reflection_questions: string[];
  prayer_focus: string | null;
  created_at: string;
}

export interface UserSeriesEnrollmentRow {
  id: string;
  user_id: string;
  series_id: string;
  enrolled_at: string;
  current_day: number;
  completed_days: number[];
  is_active: boolean;
  is_primary: boolean;
  last_activity_at: string;
  reminder_time: string;
  created_at: string;
}

export interface OnboardingResponsesRow {
  id: string;
  user_id: string;
  life_area_focus: string | null;
  time_available: string | null;
  experience_level: string | null;
  life_stage: string | null;
  completed_at: string;
  created_at: string;
}

// =====================================================
// CONVERSION HELPERS
// =====================================================

export function toDevotionalSeries(row: DevotionalSeriesRow): DevotionalSeries {
  return {
    id: row.id,
    slug: row.slug,
    title: row.title,
    description: row.description,
    coverImageUrl: row.cover_image_url ?? undefined,
    totalDays: row.total_days,
    topics: row.topics,
    isSeasonal: row.is_seasonal,
    seasonStartMonth: row.season_start_month ?? undefined,
    seasonStartDay: row.season_start_day ?? undefined,
    difficultyLevel: row.difficulty_level as DifficultyLevel,
    createdAt: new Date(row.created_at),
  };
}

export function toDevotionalDay(row: DevotionalDayRow): DevotionalDay {
  return {
    id: row.id,
    seriesId: row.series_id,
    dayNumber: row.day_number,
    title: row.title,
    scriptureRefs: row.scripture_refs,
    contentPrompt: row.content_prompt,
    reflectionQuestions: row.reflection_questions,
    prayerFocus: row.prayer_focus ?? undefined,
    createdAt: new Date(row.created_at),
  };
}

export function toUserSeriesEnrollment(
  row: UserSeriesEnrollmentRow,
  series?: DevotionalSeries
): UserSeriesEnrollment {
  return {
    id: row.id,
    userId: row.user_id,
    seriesId: row.series_id,
    series,
    enrolledAt: new Date(row.enrolled_at),
    currentDay: row.current_day,
    completedDays: row.completed_days,
    isActive: row.is_active,
    isPrimary: row.is_primary,
    lastActivityAt: new Date(row.last_activity_at),
    reminderTime: row.reminder_time,
    createdAt: new Date(row.created_at),
  };
}

export function toOnboardingResponses(row: OnboardingResponsesRow): OnboardingResponses {
  return {
    id: row.id,
    userId: row.user_id,
    lifeAreaFocus: row.life_area_focus ?? undefined,
    timeAvailable: row.time_available as TimeAvailable | undefined,
    experienceLevel: row.experience_level as ExperienceLevel | undefined,
    lifeStage: row.life_stage as LifeStage | undefined,
    completedAt: row.completed_at ? new Date(row.completed_at) : undefined,
  };
}

// =====================================================
// QUIZ CONFIGURATION
// =====================================================

export const ONBOARDING_QUIZ: QuizQuestion[] = [
  {
    id: 'life_area',
    question: 'What area would you like God to grow in your life?',
    field: 'lifeAreaFocus',
    isRequired: true,
    options: [
      {
        value: 'anxiety',
        label: 'Anxiety & Peace',
        description: 'Finding calm in uncertain times',
        icon: 'leaf-outline',
        mapsToSeries: 'overcoming-anxiety',
      },
      {
        value: 'marriage',
        label: 'Marriage',
        description: 'Strengthening your relationship',
        icon: 'heart-outline',
        mapsToSeries: 'strengthening-marriage',
      },
      {
        value: 'parenting',
        label: 'Parenting',
        description: 'Biblical wisdom for raising children',
        icon: 'people-outline',
        mapsToSeries: 'biblical-parenting',
      },
      {
        value: 'finances',
        label: 'Finances',
        description: 'Trusting God with your resources',
        icon: 'wallet-outline',
        mapsToSeries: 'trusting-god-finances',
      },
      {
        value: 'grief',
        label: 'Grief & Loss',
        description: 'Finding comfort in difficult seasons',
        icon: 'water-outline',
        mapsToSeries: 'dealing-grief',
      },
      {
        value: 'prayer',
        label: 'Prayer Life',
        description: 'Deepening your conversation with God',
        icon: 'hand-left-outline',
        mapsToSeries: 'deepening-prayer',
      },
      {
        value: 'knowing_god',
        label: 'Knowing God',
        description: "Understanding God's character",
        icon: 'sparkles-outline',
        mapsToSeries: 'knowing-gods-character',
      },
      {
        value: 'forgiveness',
        label: 'Grace & Forgiveness',
        description: 'Walking in freedom and extending grace',
        icon: 'sunny-outline',
        mapsToSeries: 'walking-grace-forgiveness',
      },
    ],
  },
  {
    id: 'time',
    question: 'How much time do you have for quiet time?',
    field: 'timeAvailable',
    isRequired: true,
    options: [
      {
        value: '5-10min',
        label: '5-10 minutes',
        description: 'Quick but meaningful',
        icon: 'timer-outline',
      },
      {
        value: '10-20min',
        label: '10-20 minutes',
        description: 'A solid devotional time',
        icon: 'time-outline',
      },
      {
        value: '20+min',
        label: '20+ minutes',
        description: 'Deep, unhurried reflection',
        icon: 'hourglass-outline',
      },
    ],
  },
  {
    id: 'experience',
    question: 'Where are you in your faith journey?',
    field: 'experienceLevel',
    isRequired: true,
    options: [
      {
        value: 'new',
        label: 'New to faith',
        description: 'Just beginning or exploring',
        icon: 'leaf-outline',
      },
      {
        value: 'growing',
        label: 'Growing & learning',
        description: 'Building a foundation',
        icon: 'trending-up-outline',
      },
      {
        value: 'deep',
        label: 'Going deeper',
        description: 'Looking to mature further',
        icon: 'compass-outline',
      },
    ],
  },
  {
    id: 'life_stage',
    question: "What's your current life stage?",
    field: 'lifeStage',
    isRequired: false,
    options: [
      {
        value: 'single',
        label: 'Single',
        description: 'Navigating life solo',
        icon: 'person-outline',
      },
      {
        value: 'married',
        label: 'Married',
        description: 'Building life together',
        icon: 'heart-outline',
      },
      {
        value: 'parent',
        label: 'Parent',
        description: 'Raising the next generation',
        icon: 'people-outline',
      },
      {
        value: 'empty_nester',
        label: 'Empty nester',
        description: 'A new season of life',
        icon: 'home-outline',
      },
    ],
  },
];

// =====================================================
// SERIES GRADIENTS & COLORS
// =====================================================

export const SERIES_GRADIENTS: Record<string, [string, string]> = {
  // Original series
  'overcoming-anxiety': ['#6366F1', '#4F46E5'], // Indigo - peace
  'strengthening-marriage': ['#EC4899', '#DB2777'], // Pink - love
  'biblical-parenting': ['#F59E0B', '#D97706'], // Amber - warmth
  'trusting-god-finances': ['#10B981', '#059669'], // Emerald - growth
  'dealing-grief': ['#8B5CF6', '#7C3AED'], // Purple - comfort
  'cultivating-gratitude': ['#F59E0B', '#FBBF24'], // Gold - joy
  'deepening-prayer': ['#3B82F6', '#2563EB'], // Blue - heaven
  'knowing-gods-character': ['#6366F1', '#8B5CF6'], // Indigo-purple - mystery
  'walking-grace-forgiveness': ['#22C55E', '#16A34A'], // Green - renewal
  'hearing-gods-voice': ['#06B6D4', '#0891B2'], // Cyan - clarity
  'advent': ['#DC2626', '#B91C1C'], // Red - Christmas
  'lent': ['#7C3AED', '#6D28D9'], // Purple - royalty/sacrifice
  'names-attributes-jesus': ['#EF4444', '#DC2626'], // Red - blood of Christ
  'victory-temptation': ['#F97316', '#EA580C'], // Orange - fire/passion
  'renewing-your-mind': ['#14B8A6', '#0D9488'], // Teal - freshness

  // Beginner Level
  'overcoming-fear': ['#7C3AED', '#5B21B6'], // Violet - courage
  'gods-unfailing-love': ['#EC4899', '#BE185D'], // Rose - love
  'daily-gratitude': ['#FBBF24', '#F59E0B'], // Amber - thankfulness
  'hearing-gods-voice-beginner': ['#22D3EE', '#06B6D4'], // Cyan - listening

  // Intermediate Level
  'power-of-prayer': ['#3B82F6', '#1D4ED8'], // Blue - heaven connection
  'fruit-of-the-spirit': ['#34D399', '#10B981'], // Emerald - growth
  'trusting-gods-timing': ['#A78BFA', '#8B5CF6'], // Purple - patience
  'forgiveness-healing': ['#4ADE80', '#22C55E'], // Green - restoration

  // Advanced Level
  'armor-of-god': ['#F97316', '#C2410C'], // Orange - battle/fire
  'attributes-of-god': ['#818CF8', '#6366F1'], // Indigo - divine mystery
  'faith-in-trials': ['#FB7185', '#F43F5E'], // Rose - perseverance
  'discipleship-obedience': ['#2DD4BF', '#14B8A6'], // Teal - commitment

  // Seasonal
  'advent-waiting-hope': ['#EF4444', '#DC2626'], // Red - Christmas anticipation
  'lent-journey-cross': ['#A855F7', '#7C3AED'], // Purple - sacrifice
  'easter-triumph': ['#FCD34D', '#FBBF24'], // Gold - resurrection glory

  // Family-focused
  'family-faith-builders': ['#F472B6', '#EC4899'], // Pink - family love
  'gods-promises-families': ['#60A5FA', '#3B82F6'], // Blue - covenant
  'fruit-spirit-home': ['#4ADE80', '#22C55E'], // Green - growing together

  // For Men
  'man-of-valor': ['#64748B', '#475569'], // Slate - strength
  'strength-in-lord': ['#0EA5E9', '#0284C7'], // Sky - power
  'leading-like-christ': ['#6366F1', '#4F46E5'], // Indigo - leadership

  // For Women
  'woman-of-grace': ['#F9A8D4', '#F472B6'], // Pink - grace/beauty
  'proverbs-31-heart': ['#C084FC', '#A855F7'], // Purple - wisdom
  'beauty-from-ashes': ['#FCA5A5', '#F87171'], // Red/coral - restoration

  // For Teenagers
  'teen-identity-christ': ['#38BDF8', '#0EA5E9'], // Sky - fresh/young
  'teen-faith-over-fear': ['#A78BFA', '#8B5CF6'], // Violet - courage
  'teen-live-boldly': ['#FB923C', '#F97316'], // Orange - boldness
};

export function getSeriesGradient(slug: string): [string, string] {
  return SERIES_GRADIENTS[slug] || ['#6366F1', '#4F46E5']; // Default indigo
}
